"""new

Revision ID: 29213898452b
Revises: c9592e062d5b
Create Date: 2023-11-06 22:33:16.281203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29213898452b'
down_revision = 'c9592e062d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
