"""new

Revision ID: 33a3a6fb60f5
Revises: fbe32c7d1bf8
Create Date: 2023-11-07 14:16:41.513133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a3a6fb60f5'
down_revision = 'fbe32c7d1bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_claims_item_name_items'), 'items', ['item_name'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_claims_item_name_items'), type_='foreignkey')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
