"""new4

Revision ID: d04dcf3711e6
Revises: 33a3a6fb60f5
Create Date: 2023-11-07 14:18:39.901093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04dcf3711e6'
down_revision = '33a3a6fb60f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claims_item_id_items', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_claims_item_id_items', 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###
