"""Initial migration

Revision ID: d7acdceac47f
Revises: 
Create Date: 2023-11-01 11:57:49.084089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7acdceac47f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reported_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_reported_id'], ['users.id'], name=op.f('fk_items_user_reported_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_claims_item_id_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_claims_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('lostitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lostitem_id'], ['items.id'], name=op.f('fk_comments_lostitem_id_items')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rewardamount', sa.String(), nullable=True),
    sa.Column('lostitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lostitem_id'], ['items.id'], name=op.f('fk_rewards_lostitem_id_items')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('payer_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], name=op.f('fk_payments_payer_user_id_users')),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], name=op.f('fk_payments_reward_id_rewards')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('rewards')
    op.drop_table('comments')
    op.drop_table('claims')
    op.drop_table('items')
    op.drop_table('users')
    # ### end Alembic commands ###
